In [35]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import re
import string
from sklearn.model_selection import train_test_split as tts
from sklearn.feature_extraction.text import CountVectorizer as CV
from sklearn.naive_bayes import MultinomialNB as NB
from sklearn.metrics import classification_report as cr
from sklearn.metrics import confusion_matrix as cm
from sklearn.metrics import accuracy_score as AS

In [37]:
df = pd.read_csv('email_spam.csv',encoding='latin1')

In [39]:
df.head()

,label,message,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

In [41]:
df['label'] = df['label'].map({'ham':0,'spam':1})

In [43]:
df.head()

,label,message,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,0,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,0,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,1,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,0,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,0,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

In [45]:
#preprocessing the data
def preProcessing(text):
    text = text.lower()
    text = re.sub(r'\d+', '', text)  # remove digits
    text = text.translate(str.maketrans('', '', string.punctuation))  # remove punctuation
    text = text.strip()
    return text

In [47]:
df['message'] = df['message'].apply(preProcessing)

In [71]:
#splitting the data
X = df['message']
y = df['label']

vectorizer = CV()
X = vectorizer.fit_transform(X)

Xtrain,Xtest,ytrain,ytest = tts(X,y,test_size=0.3,random_state=42)

In [73]:
#creating the pipeline and training the model
model = NB()

In [75]:
model.fit(Xtrain,ytrain)

MultinomialNB()

In [77]:
#evaluation of model
pred = model.predict(Xtest)

In [79]:
print("Accuracy:",AS(ytest,pred))

Accuracy: 0.9730861244019139

In [81]:
print("Confusion matrix:\n",cm(ytest,pred))

Confusion matrix:
 [[1429   24]
 [  21  198]]

In [83]:
print("Classification Report:\n",cr(ytest,pred))

Classification Report:
               precision    recall  f1-score   support

           0       0.99      0.98      0.98      1453
           1       0.89      0.90      0.90       219

    accuracy                           0.97      1672
   macro avg       0.94      0.94      0.94      1672
weighted avg       0.97      0.97      0.97      1672

In [95]:
#testing new inputs
new_inp = input("Enter a message to check:\n")
count = vectorizer.transform([new_inp])
res = model.predict(count)
if(res[0]==1):
    print("Spam\n")
else:
    print("Ham\n")

Enter a message to check:
 Subject: Work from Home and Earn $500/day!  Tired of your 9–5? Start working from home today and earn up to $500 per day. No experience needed!  [Join Now]  Limited spots available. Don’t miss this life-changing opportunity.

Ham